version: "3.9"

services:
  masq_app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      
  masq_db:
    image: "postgres"
    environment:
      POSTGRES_USER: boink
      POSTGRES_PASSWORD: password
      POSTGRES_DB: masq_forms
