version: "3.9"

services:
  masq_db:
    container_name: pg
    image: "postgres"
    volumes:
      - ./samples:/opt
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_ADDRESS: ${DB_ADDRESS}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  masq_app:
    container_name: app
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      DB_URI: "postgresql://${DB_USER}:${DB_PASS}@${DB_ADDRESS}:${DB_PORT}/${DB_NAME}"
