version: "3.9"

services:
  masq_nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./app.conf.template:/etc/nginx/templates/app.conf.template
    ports:
      - "80:80"
    environment:
      NGINX_PORT: 80
      DOMAIN_NAME: ${DOMAIN_NAME}

  masq_db:
    container_name: pg
    image: "postgres"
    volumes:
      - ./samples:/opt
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_ADDRESS: ${DB_ADDRESS}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  masq_app:
    container_name: app
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app/app.py
      FLASK_DEBUG: 1
      DB_PORT: ${DB_PORT}
      DB_URI: "postgresql://${DB_USER}:${DB_PASS}@${DB_ADDRESS}:${DB_PORT}/${DB_NAME}"
