"""empty message

Revision ID: 99fa853c6582
Revises: 
Create Date: 2022-05-29 10:31:15.921922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99fa853c6582'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('hostname', sa.String(length=30), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('extra_ips', sa.String(length=30), nullable=False),
    sa.Column('functions', sa.String(length=30), nullable=False),
    sa.Column('subsystems', sa.String(length=30), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forms_table')
    # ### end Alembic commands ###
